x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    mem_limit: 500m
    cpus: "0.20"
    logging: *default-logging
    restart: unless-stopped
    networks:
      - perpix
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - /opt/perpix/.env

networks:
  perpix:
    external: true

volumes:
  caddy_data:
  caddy_config:
