x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    mem_limit: 500m
    cpus: "0.20"
    logging: *default-logging
    volumes:
      - n8n-data:/home/node/.n8n
    environment:
      GENERIC_TIMEZONE: UTC
      N8N_HOST: n8n.perpixai.com
      N8N_PROTOCOL: https
      N8N_EDITOR_BASE_URL: https://n8n.perpixai.com/
      WEBHOOK_URL: https://n8n.perpixai.com/
      N8N_DIAGNOSTICS_ENABLED: "false"
    restart: unless-stopped
    networks:
      - perpix
    env_file:
      - /opt/perpix/.env

volumes:
  n8n-data:

networks:
  perpix:
    external: true
